print("Average speed")
d=int(input("Distance (in meters or kilometers)="))
t=int(input("Time (in hours or second)="))
print("distance")
d1=float(input("distance1="))
d2=float(input("distance2="))
print("displacement")
df=float(input("distancef="))
di=float(input("distancei="))
print("velocity")
dt=float(input("Distance (in meters or kilometers with direction)="))
tt=float(input("Time (in hours or second)="))
print("Vav=",d,"/",t,"=",round(d/t,2))
print("dt=",d1,"+",d2,"=",round(d1+d2))
print("d->=",df,"-",di,"=",round(df-di))
print("vav->=",dt,"/",tt,"=",round(dt/tt,2))

