#By: Benji Saltz
#date:9/816
#Description: Output and Data type exercises

print("Question 1")
print("python Rocks!")
print("Question 2")
print("Computer Science")
print("        @       ")
print("  Westmount CI  ")
print("Question 3")
print(round(0.13*867.53+867.53,2))
print("Question 4")
print(" 232 minuites converted into hours and minuites =")
print("hours=", abs(232//60))
print("minuites=", 232%60)
print("Question 5")
import math
print("The circumference of a circle  with a diameter of six =",round(math.pi*6,3))
print("Question 6")
print(round((17+24+30)/3,3))
print("Question 7")
print("World Cup Brazil"+" 2014")
print("Question 8")
print(ord('P'), " ", ord('i'))
##print("Question 9")
##int(25)
##int(25.7)
##int('25')
##int('25.7')
##bool(5)
##bool(0)
##bool('blah')
##bool("")
##bin(57)
##bin(257)
##chr(82)
##chr(114)

